### ISSUE TITLE
Specify PVC Storage Class Name

### ISSUE THREAD

**Issue by mathianasj** [dev4devs-com/postgresql-operator#69]
### Is your feature request related to a problem? Please describe.
I do not have default storage classes defined, and need to specify which storageclassname the pvc should request.

### Describe the solution you'd like
Have the ability to specify the storageclassname in the CRD.

**Comment by camilamacedo86** [comment]
Done. It will be in the next release and please feel free to contribute with this Project. 
Your Pr's are very welcome.
