### ISSUE TITLE
Any plan to upgrade the Operator from `v1beta1` to `v1`?

### ISSUE THREAD

**Issue by dharmit** [dev4devs-com/postgresql-operator#78]
### What did you do?

Tried to install the Operator on OCP 4.9 using steps mentioned in https://github.com/openshift/odo/issues/4961.

### What did you expect to see?

Operator to get installed and available for use

### What did you see instead? Under which circumstances?

Copied from [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1997411#c1)
```shell
$ k logs catalog-operator-55f45c8665-zg6nn | grep apiextensions.k8s.io/v1beta1
E0825 15:50:44.863539       1 queueinformer_operator.go:290] sync {"update" "test/install-8qsnt"} failed: api-server resource not found installing CustomResourceDefinition backups.postgresql.dev4devs.com: GroupVersionKind apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition not found on the cluster. This API may have been deprecated and removed, see https://kubernetes.io/docs/reference/using-api/deprecation-guide/ for more information.
E0825 15:50:45.312012       1 queueinformer_operator.go:290] sync {"update" "test/install-8qsnt"} failed: api-server resource not found installing CustomResourceDefinition backups.postgresql.dev4devs.com: GroupVersionKind apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition not found on the cluster. This API may have been deprecated and removed, see https://kubernetes.io/docs/reference/using-api/deprecation-guide/ for more information.
E0825 15:50:46.116916       1 queueinformer_operator.go:290] sync {"update" "test/install-8qsnt"} failed: api-server resource not found installing CustomResourceDefinition backups.postgresql.dev4devs.com: GroupVersionKind apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition not found on the cluster. This API may have been deprecated and removed, see https://kubernetes.io/docs/reference/using-api/deprecation-guide/ for more information.
...
```

### Environment
~* postgresql-operator version: `0.1.1 (Current)` (used the one from https://operatorhub.io/operator/postgresql-operator-dev4devs-com)~ 

(Confused above with minikube)
* postgresql-operator version: Used the one available on OCP 4.9

* Kubernetes version information:

* Kubernetes cluster kind: OpenShift 4.9

### Additional context

Looking at https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/138, it seems like the PostgreSQL Operator will no longer be installed on OCP 4.9 as it uses `v1beta1` API. Are there plans to upgrade the Operator to use `v1` API?

**Comment by camilamacedo86** [comment]
Hi @dharmit, 

I have no time to do that. However, if you be able to do it your contribution is very welcome. 
I'd recommend migrate the project to use the latest version of SDK, by following the doc: https://sdk.operatorframework.io/docs/building-operators/golang/migration/

Then, we need to generate the bundle and publish it in: https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators and in: https://github.com/operator-framework/community-operators

Would you like to help out? 
I can review your contributions.

**Comment by dharmit** [comment]
Hi @camilamacedo86. Unfortunately, I'm in a tight spot as well and can't help with the effort at this point. 😞
